from manim import *
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from manim_voiceover import VoiceoverScene
from services.piper_service import PiperTTSService

class ImagioScene(VoiceoverScene):
    def construct(self):
        self.camera.background_color = "#0f0f23"
        self.set_speech_service(PiperTTSService(voice='en_US-lessac-medium'))

        _footer = Text('Made by Imagio', font_size=15, color=WHITE)
        _footer.to_corner(DR, buff=0.25)
        self.add(_footer)

        self.wait(0.5)  # scene entry buffer

        title = Text('Why Decompose Signals?', font_size=44, color=WHITE, weight=BOLD)
        title.to_edge(UP, buff=0.4)
        self.play(Write(title), run_time=0.8, rate_func=smooth)
        self.wait(0.3)

        # Image generated by Nebius FLUX from: 'A chaotic waveform composed of many overlapping colors, with individual colored sine wave components extracted and displayed separately, scientific illustration, clean white background'
        _image_path = 'E:\\random\\Imagio\\Imagio\\workspace\\media\\generated\\pic_f0d4d92a0918.png'
        if _image_path and os.path.exists(_image_path):
            image = ImageMobject(_image_path)
            image.set_height(4.0)
        else:
            _ph_bg  = Rectangle(width=5.0, height=3.6,
                fill_color='#2a2a4a', fill_opacity=1,
                stroke_color='#666688', stroke_width=2)
            _ph_lbl = Text('[ Image ]', font_size=26, color='#666688')
            _ph_lbl.move_to(_ph_bg.get_center())
            image   = VGroup(_ph_bg, _ph_lbl)
        image.move_to(LEFT * 2.8 + DOWN * 0.3)
        with self.voiceover(text='Imagine listening to a symphony where every instrument plays at once; our ears can still pick out the melody because the sound can be split into individual notes. In the same way, any complicated signal—whether it’s a sound clip, an image, or a sensor reading—can be broken down into simple sine waves. By representing a signal as a collection of pure frequencies, we reveal hidden structure, make analysis tractable, and open the door to powerful tools like the Fourier transform.'):
            self.play(FadeIn(image, shift=RIGHT * 0.15), run_time=0.8, rate_func=smooth)
        self.wait(0.3)

        caption_obj = Text('Complex signals are sums of simple sine waves.', font_size=20,
            color='#a0a8d0', slant=ITALIC)
        caption_obj.next_to(image, DOWN, buff=0.2)
        self.play(FadeIn(caption_obj, shift=UP * 0.1), run_time=0.5)
        self.wait(0.25)

        # body_text font size: 40 words -> 16pt
        body = Text('Any time‑varying signal can be expressed as a combination of sinusoidal components. Each sine wave carries a specific frequency, amplitude, and phase, which together capture the signal’s shape. Separating these components lets us analyze, filter, and compress data more effectively.', font_size=16,
            color=WHITE, line_spacing=1.4)
        body.set_width(4.8)
        body.move_to(RIGHT * 3.0 + DOWN * 0.3)
        if body.height > 5.0:
            body.scale(5.0 / body.height)
        self.play(FadeIn(body, shift=LEFT * 0.15), run_time=0.9, rate_func=smooth)
        self.wait(0.3)

        self.wait(2)
        self.play(FadeOut(*self.mobjects), run_time=0.8)
        self.wait(0.5)  # scene exit buffer
