from manim import *
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from manim_voiceover import VoiceoverScene
from services.piper_service import PiperTTSService

class ImagioScene(VoiceoverScene):
    def construct(self):
        self.camera.background_color = "#0f0f23"
        self.set_speech_service(PiperTTSService(voice='en_US-lessac-medium'))

        _footer = Text('Made by Imagio', font_size=15, color=WHITE)
        _footer.to_corner(DR, buff=0.25)
        self.add(_footer)

        self.wait(0.5)  # scene entry buffer

        title = Text('Light Cones Near a Black‑Hole Horizon', font_size=38, color=WHITE, weight=BOLD)
        title.to_edge(UP, buff=0.4)
        self.play(Write(title), run_time=0.8, rate_func=smooth)
        self.wait(0.3)

        # Image generated by Nebius FLUX from: 'Illustration on white background of two spacetime diagrams: an upright light cone far from a mass and a heavily tilted cone at the Schwarzschild radius.'
        _image_path = 'E:\\random\\Imagio\\Imagio\\workspace\\media\\generated\\pic_e0f57bd0069f.png'
        if _image_path and os.path.exists(_image_path):
            image = ImageMobject(_image_path)
            image.set_height(4.0)
        else:
            _ph_bg  = Rectangle(width=5.0, height=3.6,
                fill_color='#2a2a4a', fill_opacity=1,
                stroke_color='#666688', stroke_width=2)
            _ph_lbl = Text('[ Image ]', font_size=26, color='#666688')
            _ph_lbl.move_to(_ph_bg.get_center())
            image   = VGroup(_ph_bg, _ph_lbl)
        image.move_to(LEFT * 2.8 + DOWN * 0.3)
        with self.voiceover(text='When we draw spacetime on a piece of paper, the path that light can travel forms a 45‑degree cone. Near a massive object the fabric of spacetime stretches, and those cones tip inward. At the Schwarzschild radius the tilt becomes so extreme that the future‑directed cone points entirely toward the center; any future‑directed path stays inside. That means once you cross the horizon, every possible direction you could move leads deeper, so nothing—not even light—can get out. The diagram shows two cones: one far away, upright, and one right at the horizon, almost lying flat, illustrating the causal barrier.'):
            self.play(FadeIn(image, shift=RIGHT * 0.15), run_time=0.8, rate_func=smooth)
        self.wait(0.3)

        caption_obj = Text('Light cones tilt inward as gravity strengthens, becoming horizontal at the event horizon.', font_size=20,
            color='#a0a8d0', slant=ITALIC)
        caption_obj.next_to(image, DOWN, buff=0.2)
        self.play(FadeIn(caption_obj, shift=UP * 0.1), run_time=0.5)
        self.wait(0.25)

        # body_text font size: 51 words -> 16pt
        body = Text('A light cone marks all possible directions that light—or any causal influence—can travel from a given event. Near a massive object the cone tilts toward the mass, reflecting that future paths are pulled inward. At the Schwarzschild radius the cone lies flat, so every future‑directed path stays inside, making escape impossible.', font_size=16,
            color=WHITE, line_spacing=1.4)
        body.set_width(4.8)
        body.move_to(RIGHT * 3.0 + DOWN * 0.3)
        if body.height > 5.0:
            body.scale(5.0 / body.height)
        self.play(FadeIn(body, shift=LEFT * 0.15), run_time=0.9, rate_func=smooth)
        self.wait(0.3)

        self.wait(2)
        self.play(FadeOut(*self.mobjects), run_time=0.8)
        self.wait(0.5)  # scene exit buffer
